# MODEL
backbone: ~
backbone_weights: ~
freeze_backbone: ~

head: ~
head_weights: ~
num_classes: ~
embedding_size: ~
net: simclr # choose among [simclr, simclr34_norm, simclr50_norm, simclr50_v2, fc_head, fc_head_dino384, cell_classifier, resnet, vit_small]

# DIRECTORIES
checkpoint_dir: ~
dataset_dir: /work/ai4bio2024/rxrx1
load_checkpoint: ~

# TRAINING OPTIONS
epochs: 20
batch_size: 256
loss: NCE # choose among [NCE, cross_entropy]
opt: adam # choose among [adam,]
collate_fun: simclr_collate # chose among [simclr_collate, simple_collate, dino_test_collate, channelnorm_collate]
lr: 0.005
evaluation_freq: 4
model_save_freq: 4
log_accuracy: False # choose among [True, False]
grouper: ~ # choose among [experiment, cell_type, ...]
sched_pow: 1.5

# HARDWARE
device: gpu
multiple_gpus: False
train_workers: 7
evaluation_workers: 7

# WNADB CONFIG
project_name: "AIBIO_proj"
run_name: "simclr_train"