# MODEL
backbone: ~
backbone_weights: ~

head: ~
num_classes: ~

net: simclr # choose among [simclr, simclr34_norm, simclr50_norm, simclr50_v2, fc_head, cell_classifier, resnet]

# CONFIGS FOR MODELS THAT DROP THE FC HEAD
drop_head: ~ # choose among [~ , True, False]
embedding_size: ~ #default: 512

# DIRECTORIES
checkpoint_dir: /work/h2020deciderficarra_shared/rxrx1/checkpoints/simclr_backbone
dataset_dir: /work/ai4bio2024/rxrx1
load_checkpoint: ~

# TRAINING OPTIONS
epochs: 20
batch_size: 256
loss: NCE # choose among [NCE, cross_entropy]
opt: adam # choose among [adam,]
collate_fun: simclr_collate # chose among [simclr_collate, simple_collate]
lr: 0.005
evaluation_freq: 4
model_save_freq: 4
grouper: ~ # choose among [experiment, cell_type, ...]
sched_pow: 1.5

# HARDWARE
device: gpu
multiple_gpus: False
train_workers: 7
evaluation_workers: 7

# WNADB CONFIG
project_name: "AIBIO_proj"
run_name: "simclr_train"