# MODEL
net: resnet
num_classes: 1139

# DIRECTORIES
checkpoint_dir: D:\temp
dataset_dir: D:\Datasets

# TRAINING OPTIONS
epochs: 10
batch_size: 16
loss: cross_entropy
opt: adam
evaluation_freq: 1
model_save_freq: 10

# HARDWARE
device: gpu
multiple_gpus: False
train_workers: 1
evaluation_workers: 1