batch_size: 16
dataset_dir: D:\Datasets
checkpoint_dir: D:\Datasets\checkpoints
device: gpu
epochs: 1
net: simclr
loss: NCE
opt: adam
evaluation_freq: 4
model_save_freq: 4
multiple_gpus: False

train_workers: 1
evaluation_workers: 1