batch_size: 256
dataset_dir: /work/ai4bio2024/rxrx1
checkpoint_dir: /work/ai4bio2024/rxrx1/checkpoints/simclr
device: gpu
epochs: 12
net: simclr
loss: NCE
opt: adam
evaluation_freq: 4
model_save_freq: 4
multiple_gpus: True
# load_checkpoint: /work/ai4bio2024/rxrx1/checkpoints/simclr/checkpoint4