batch_size: 128
dataset_dir: /work/ai4bio2024/rxrx1
checkpoint_dir: /homes/nmorelli/checkpoints/simclr
device: gpu
epochs: 4
net: simclr
loss: contrastive
opt: adam
evaluation_freq: 4
model_save_freq: 4
multiple_gpus: True