# MODEL
net: simclr
# load_checkpoint: D:\checkpoints\checkpoint4

# DIRECTORIES
checkpoint_dir: /work/ai4bio2024/rxrx1/checkpoints/simclr/
dataset_dir: /work/ai4bio2024/rxrx1

# TRAINING OPTIONS
epochs: 20
batch_size: 128
loss: NCE
opt: adam
evaluation_freq: 4
model_save_freq: 1

# HARDWARE
device: gpu
multiple_gpus: True
train_workers: 6
evaluation_workers: 6