# MODEL
net: simclr
load_checkpoint: D:\checkpoints\checkpoint4

# DIRECTORIES
checkpoint_dir: D:\temp
dataset_dir: D:\Datasets

# TRAINING OPTIONS
epochs: 10
batch_size: 16
loss: NCE
opt: adam
evaluation_freq: 4
model_save_freq: 1

# HARDWARE
device: gpu
multiple_gpus: False
train_workers: 1
evaluation_workers: 1