# MODEL
backbone: vit_small
backbone_weights: /work/h2020deciderficarra_shared/rxrx1/checkpoints/dino/folds/f3/checkpoint0098.pth
freeze_backbone: True

head: fc_head
embedding_size: 384
head_weights: ~
num_classes: 1139

net: cell_classifier
load_checkpoint: ~


# DIRECTORIES
checkpoint_dir: /work/h2020deciderficarra_shared/rxrx1/checkpoints/dino/folds/f3/head
dataset_dir: /work/h2020deciderficarra_shared/rxrx1/rxrx1_orig
metadata_path: /work/h2020deciderficarra_shared/rxrx1/rxrx1_orig/metadatas/meta_3.csv

# TRAINING OPTIONS
cell_type: huvec  # chose [all, huvec]
epochs: 200
batch_size: 128
collate_fun: tuple_channelnorm_collate_head
loss: cross_entropy
opt: adam
lr: 0.005
evaluation_freq: 1
log_accuracy: True
model_save_freq: 5
grouper: ~
sched_pow: 1.5

# HARDWARE
device: gpu
multiple_gpus: False
train_workers: 16
evaluation_workers: 16

# WANDB CONFIG
project_name: "AIBIO_proj"
run_name: "head_f3"
